{%- set cc = cookiecutter -%}
{%- raw -%}
# Please ensure the following GitHub repository action secrets are set up:
#  - GH_TOKEN
#  - DOCKER_REGISTRY_USER
#  - DOCKER_REGISTRY_PASSWORD

name: Setup
description: Setup for all CI workflows
{%- endraw %}

inputs:
  repo:
    default: "{{ cc.repo }}"
    description: Repository name
    required: true

  org:
    default: "{{ cc.git_organization }}"
    description: GitHub organization
    required: true

  org_url:
    default: "{{ cc.organization_url }}"
    description: Company URL
    required: true

  docker_registry:
    default: "{{ cc.docker_registry }}"
    description: Docker registry
    required: true

  docker_registry_user:
    description: Docker registry user
    required: true

  docker_registry_password:
    description: Docker registry password
    required: true

{% raw -%}
runs:
  using: composite
  steps:
      - name: Change repo permissions
        shell: bash
        run: chmod -R o+w ../

      - name: Configure git
        shell: bash
        run: |
          git config --global user.name ci && \
          git config --global user.email "ci@${{ inputs.org_url }}"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ inputs.docker_registry_user }}
          password: ${{ inputs.docker_registry_password }}
{% endraw %}

{%- if cc.include_secret_env == 'yes' %}
      - name: Write PyPI access token to secret-env
        shell: bash
        run: |
          echo "export PYPI_ACCESS_TOKEN=$PYPI_ACCESS_TOKEN" \
            > docker/config/secret-env
{%- endif %}
