default_context:
  repo: datalus
  repo_type: package
  include_openexr: no
  port_prefix: 99
  github_user: theNewFlesh
  description: A cloud-native, custom dashboard and ephemeral database application.
  author: Alex Braun
  email: alexander.g.braun@gmail.com
  website: http://www.alexgbraun.com
  volume: ''
  keywords: data, cloud, app
  year: 2021
