default_context:
  repo: datalus-repo
  repo_type: dash
  include_openexr: "yes"
  include_tensorflow: "yes"
  port_prefix: 99
  git_user: thenewflesh
  git_host: gitlab
  description: A cloud-native, custom dashboard and ephemeral database application.
  author: Alex Braun
  email: alexander.g.braun@gmail.com
  website: http://www.alexgbraun.com
  volume: ""
  keywords: data, cloud, app
  year: 2023
  python_min_version: 7
  python_max_version: 10
