default_context:
  repo: datalus
  repo_type: library
  include_gcc: "no"
  include_helm: "no"
  include_mkdocs: "yes"
  include_nvidia: "no"
  include_openexr: "yes"
  include_prod_cli: "no"
  include_prod_envs: "yes"
  include_secret_env: "yes"
  include_vscode_server: "yes"
  port_prefix: 99
  git_user: theNewFlesh
  git_host: gitlab
  git_organization: theNewFlesh
  docker_registry: gitlab
  organization_url: mycompany.com
  description: A cloud-native, custom dashboard and ephemeral database application.
  author: Alex Braun
  email: alexander.g.braun@gmail.com
  website: https://www.alexgbraun.com
  volume: "/tmp/storage"
  keywords: data, cloud, app
  year: 2023
  python_min_version: 7
  python_max_version: 13
  initial_repo_version: "0.1.0"
