{%- raw -%}
name: Master
run-name: "${{ github.event.head_commit.message }} | ${{ github.actor }}"

on:
  push:
    branches: [ master ]

env:
  cli: "bin/${{ github.event.repository.name }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build dev image
        uses: ./.github/actions/build

      - name: Start container
        run: $cli docker-start

      - name: Version bump
        run: $cli version-bump

      - name: Version
        run: $cli version

      - name: Commit new version
        run: $cli version-commit

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Push dev image
        run: $cli docker-push-dev

      - name: Push dev-latest image
        run: $cli docker-push-dev-latest

  pages:
    needs: master
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
{% endraw %}
