{%- set cc = cookiecutter -%}
{%- raw -%}
name: Master
run-name: "Master - ${{ github.head_ref }} - ${{ github.actor }}"

on:
  push:
    branches: [ master ]

env:
  repo: "${{ github.event.repository.name }}"
  cli: "bin/${{ github.event.repository.name }}"
{%- endraw %}
  org: "{{ cc.git_organization }}"
  org_url: "{{ cc.organization_url }}"
  docker_registry: "{{ cc.docker_registry }}"
  BUILDKIT_PROGRESS: tty
{%- raw %}

jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Change repo permissions
        run: chmod -R o+w ../

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.docker_registry }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Pull image
        run: $($cli docker-pull-dev) || echo "docker image not found"

      - name: Build image
        run: $cli docker-build-from-cache

      - name: Start container
        run: $cli docker-start

      - name: Version bump
        run: $cli version-bump-patch

      - name: Version
        run: $cli version

      - name: Commit new version
        run: $cli version-commit

      - name: Push dev image
        run: $cli docker-push-dev

      - name: Push dev-latest image
        run: $cli docker-push-dev-latest

  pages:
    needs: master
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

{% endraw %}