{%- raw -%}
name: Master Pull Request
run-name: "PR: ${{ github.head_ref }} --> master | ${{ github.actor }}"

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

env:
  cli: "bin/${{ github.event.repository.name }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  master-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Pull image
        run: $cli docker-pull-dev || echo "docker image not found"

      - name: Build image
        run: $cli docker-build-from-cache

      - name: Start container
        run: $cli docker-start

      - name: Generate docs
        run: $cli docs

      - name: Generate code metrics
        run: $cli docs-metrics

      - name: Generate architecture diagram
        run: $cli docs-architecture

      - name: Lint code
        run: $cli test-lint

      - name: Run tests
        run: $cli test-coverage
{% endraw %}
