{%- raw -%}
name: Prod
run-name: "${{ github.event.head_commit.message }} | ${{ github.actor }}"

on:
  push:
    branches: [ prod ]

env:
  cli: "bin/${{ github.event.repository.name }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Pull image
        run: $cli docker-pull-dev || echo "docker image not found"

      - name: Build image
        run: $cli docker-build-from-cache

      - name: Tag image
        run: docker tag $repo:dev-latest $repo:dev

      - name: Start container
        run: $cli docker-start

      - name: Run prod tests
        run: $cli test-prod

      - name: Publish python package
        run: $cli build-publish -a ${{ secrets.PYPI_ACCESS_TOKEN }}

      - name: Build prod image
        run: $cli docker-build-prod-no-cache

      - name: Push prod image
        run: $cli docker-push-prod

      - name: Push prod-latest image
        run: $cli docker-push-prod-latest
{% endraw %}
