{%- raw -%}
name: Prod Pull Request
run-name: "PR: ${{ github.head_ref }} --> prod | ${{ github.actor }}"

on:
  pull_request:
    branches: [ prod ]
    types: [ opened, synchronize ]

env:
  cli: "bin/${{ github.event.repository.name }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  prod-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Pull image
        run: $cli docker-pull-dev || echo "docker image not found"

      - name: Build image
        run: $cli docker-build-from-cache

      - name: Tag image
        run: docker tag $repo:dev-latest $repo:dev

      - name: Start container
        run: $cli docker-start

      - name: Run prod tests
        run: $cli test-prod

    #   - name: Publish python package
    #     run: $cli build-publish-test -a ${{ secrets.PYPI_TEST_ACCESS_TOKEN }}

    #   - name: Build prod image
    #     run: $cli docker-build-prod-no-cache

    #   - name: Unpublish python package
    #     run: - $cli build-unpublish -a ${{ secrets.PYPI_ACCESS_TOKEN }}
{% endraw %}
