{%- raw -%}
name: Prod Pull Request
run-name: "PR: ${{ github.head_ref }} --> prod | ${{ github.actor }}"

on:
  pull_request:
    branches: [ prod ]
    types: [ opened, synchronize ]

env:
  cli: "bin/${{ github.event.repository.name }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  prod-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check merge branch
        if: github.head_ref != 'master'
        run: |
          echo "ERROR: Only master may be merged into prod" && \
          exit 1

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          docker_registry_user: ${{ secrets.DOCKER_REGISTRY_USER }}
          docker_registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build dev image
        uses: ./.github/actions/build

      - name: Start container
        run: $cli docker-start

      - name: Run prod tests
        run: $cli test-prod

      # - name: Publish python package
      #   run: $cli build-publish-test -a ${{ secrets.PYPI_TEST_ACCESS_TOKEN }}

      # - name: Build prod image
      #   run: $cli docker-build-prod-no-cache

      # - name: Unpublish python package
      #   run: $cli build-unpublish -a ${{ secrets.PYPI_ACCESS_TOKEN }}
{% endraw %}
