{%- set cc = cookiecutter -%}
{%- set max_ver = cc.python_max_version | int -%}
[project]
name = "pdm"
version = "{{ cc.initial_repo_version }}"
requires-python = "==3.{{ max_ver }}"
dependencies = []

{% if cc.include_secret_env == 'yes' %}
[[tool.pdm.source]]
name = "{{ cc.repo }}-index"
url = "https://__token__:${PYPI_ACCESS_TOKEN}@${
{{- cc.repo | upper | replace('-', '_') -}}
_URL}"
include_packages = ["{{ cc.repo }}"]
exclude_packages = ["*"]
{% endif -%}

[tool.pdm]
distribution = false

