{%- set cc = cookiecutter -%}
apiVersion: v2
name: {{cc.repo}}
version: {{cc.initial_repo_version}}
{%- if cc.git_host == 'github' %}
home: https://github.com/{{ cc.git_user }}/{{cc.repo}}
{% elif cc.git_host == 'gitlab' %}
home: https://gitlab.com/{{ cc.git_user }}/{{cc.repo}}
{% elif cc.git_host == 'bitbucket' %}
home: https://bitbucket.org/{{ cc.git_user }}/{{ cc.repo }}
{% endif -%}
description: |
  {{cc.description}}
keywords:
{{'  - ' + cc.keywords.split(', ')|join("\n  - ")}}
type: application
appVersion: "{{cc.initial_repo_version}}"
maintainers:
  - name: {{cc.author}}
    email: {{cc.email}}
    url: {{cc.website}}
