{%- set cc = cookiecutter -%}
enable:
  namespace: false
  argocd_application: false
  env_configmap: true
  env_secret: false
  image_pull_secret: false
  repo_volume: false
  desktop_volume: false
  nfs_volume: false
  nginx_ingress: false
  traefik_ingress: false
  readiness_probe: true
  liveness_probe: true

namespace:
  name: {{ cc.repo }}

argocd_application:
  name: {{ cc.repo }}
  source_namespace: argocd
  target_namespace: {{ cc.repo }}

env_configmap:
  FLASK_APP: server.app:get_app
  FLASK_DEBUG:
  FLASK_RUN_PORT: 8080
  FLASK_RUN_HOST: 0.0.0.0

env_secret:

deployment:
  repository: {{ cc.git_user }}/{{ cc.repo }}
  image_tag: latest
  repo_path: /home/ubuntu/{{ cc.repo }}
  storage_path: /mnt/storage
  image_pull_policy: IfNotPresent
  nfs_server:
  command:
    - {{ cc.repo }}
    - server
  args:
  env_configmap: {{ cc.repo }}-env-configmap
  env_secret: {{ cc.repo }}-env-secret

service:
  port: 80
  target_port: 8080

repo_volume:
  path:

desktop_volume:
  path:

nginx_ingress:
  host:

traefik_ingress:
  match:

image_pull_secret:
  docker_config:
