{%- set cc = cookiecutter -%}
{%- raw -%}
{{- with (include "overlay" . | fromYaml) -}}
{{ if .enable.argocd_application }}
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ .argocd_application.name }}
  namespace: {{ .argocd_application.source_namespace }}
spec:
  project: default
  source:
{%- endraw -%}
{%- if cc.git_host == 'github' %}
repoURL: https://github.com/{{cc.git_user}}/{{cc.repo}}.git
{% elif cc.git_host == 'gitlab' %}
repoURL: https://gitlab.com/{{cc.git_user}}/{{cc.repo}}.git
{% elif cc.git_host == 'bitbucket' %}
repoURL: https://bitbucket.org/{{cc.git_user}}/{{cc.repo}}.git
{% endif -%}
{%- raw -%}
    targetRevision: master
    path: helm
    helm:
      values: |
        overlay: rancher_desktop
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .argocd_application.target_namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
{{- end -}}
{%- endraw %}
