{%- raw %}
{{- with (include "overlay" . | fromYaml) -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ cookiecutter.repo }}
  namespace: {{ .namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .argocd_application.name }}
  template:
    metadata:
      labels:
        app: {{ .argocd_application.name }}
    spec:
      containers:
        - name: {{ .argocd_application.name }}-container
          image: "{{ .deployment.repository }}:{{ .deployment.image_tag }}"
          imagePullPolicy: {{ .deployment.image_pull_policy }}
          command:
          {{- range $item := .deployment.command }}
            - {{ $item }}
          {{- end }}
          args:
          {{- range $item := .deployment.args }}
            - {{ $item }}
          {{- end }}
          envFrom:
            {{- if .enable.env_configmap }}
            - configMapRef:
                name: {{ .argocd_application.name }}-env-configmap
            {{- end }}
            {{- if .enable.env_secret }}
            - secretRef:
                name: {{ .argocd_application.name }}-env-secret
            {{- end }}
          ports:
            - containerPort: {{ .service.target_port }}
          {{- if .enable.liveness_probe }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- end }}
          {{- if .enable.readiness_probe }}
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ .deployment.storage_path }}
            {{- if .enable.repo_volume }}
            - name: repo
              mountPath: {{ .deployment.repo_path }}
            {{- end }}
      volumes:
      {{- if .enable.nfs_volume }}
        - name: storage
          nfs:
             path: {{ .deployment.storage_path }}
             server: {{ .deployment.nfs_server }}
             readOnly: false
      {{- else if .enable.desktop_volume }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .argocd_application.name }}-storage-pvc
      {{- end }}
      {{- if .enable.repo_volume }}
        - name: repo
          persistentVolumeClaim:
            claimName: {{ .argocd_application.name }}-repo-pvc
      {{- end }}
      imagePullSecrets:
        - name: image-pull-secret
{{- end -}}
{%- endraw %}