{%- raw -%}
{{- with (include "overlay" . | fromYaml) -}}
{{ if .enable.traefik_ingress }}
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: {{ .argocd_application.name }}-traefik-ingress
  namespace: {{ .namespace.name }}
spec:
  routes:
    - match: {{ .traefik_ingress.match }}
      kind: Rule
      services:
        - name: {{ .argocd_application.name }}-service
          kind: Service
          port: 80
{{ end }}
{{- end -}}
{%- endraw %}