site_name: {{cookiecutter.repo}}
theme: readthedocs
docs_dir: md
site_dir: ../docs
use_directory_urls: False
extra:
  version: {{cookiecutter.initial_repo_version}}
extra_css:
  - style.css
nav:
  - Introduction: index.md
