site_name: {{cookiecutter.repo}}
theme: readthedocs
docs_dir: md
{% if cookiecutter.git_host == 'gitlab' %}
site_dir: ../public
{% else %}
site_dir: ../docs
{% endif %}
use_directory_urls: False
extra:
  version: {{cookiecutter.initial_repo_version}}
extra_css:
  - style.css
nav:
  - Introduction: index.md
